// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/koungkub/fw-challenge-notification-service/internal/service (interfaces: NotificationProvider)
//
// Generated by this command:
//
//	mockgen -package mockservice -destination ./mock/mockservice.go . NotificationProvider
//

// Package mockservice is a generated GoMock package.
package mockservice

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificationProvider is a mock of NotificationProvider interface.
type MockNotificationProvider struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationProviderMockRecorder
	isgomock struct{}
}

// MockNotificationProviderMockRecorder is the mock recorder for MockNotificationProvider.
type MockNotificationProviderMockRecorder struct {
	mock *MockNotificationProvider
}

// NewMockNotificationProvider creates a new mock instance.
func NewMockNotificationProvider(ctrl *gomock.Controller) *MockNotificationProvider {
	mock := &MockNotificationProvider{ctrl: ctrl}
	mock.recorder = &MockNotificationProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationProvider) EXPECT() *MockNotificationProviderMockRecorder {
	return m.recorder
}

// SendToBuyer mocks base method.
func (m *MockNotificationProvider) SendToBuyer(ctx context.Context, to, title, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendToBuyer", ctx, to, title, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendToBuyer indicates an expected call of SendToBuyer.
func (mr *MockNotificationProviderMockRecorder) SendToBuyer(ctx, to, title, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToBuyer", reflect.TypeOf((*MockNotificationProvider)(nil).SendToBuyer), ctx, to, title, message)
}

// SendToSeller mocks base method.
func (m *MockNotificationProvider) SendToSeller(ctx context.Context, to, title, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendToSeller", ctx, to, title, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendToSeller indicates an expected call of SendToSeller.
func (mr *MockNotificationProviderMockRecorder) SendToSeller(ctx, to, title, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToSeller", reflect.TypeOf((*MockNotificationProvider)(nil).SendToSeller), ctx, to, title, message)
}
