// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/koungkub/fw-challenge-notification-service/internal/repository (interfaces: CacheProvider)
//
// Generated by this command:
//
//	mockgen -package mockrepository -destination ./mock/mockcache.go . CacheProvider
//

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	reflect "reflect"

	repository "github.com/koungkub/fw-challenge-notification-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockCacheProvider is a mock of CacheProvider interface.
type MockCacheProvider struct {
	ctrl     *gomock.Controller
	recorder *MockCacheProviderMockRecorder
	isgomock struct{}
}

// MockCacheProviderMockRecorder is the mock recorder for MockCacheProvider.
type MockCacheProviderMockRecorder struct {
	mock *MockCacheProvider
}

// NewMockCacheProvider creates a new mock instance.
func NewMockCacheProvider(ctrl *gomock.Controller) *MockCacheProvider {
	mock := &MockCacheProvider{ctrl: ctrl}
	mock.recorder = &MockCacheProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheProvider) EXPECT() *MockCacheProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCacheProvider) Get(key repository.NotificationProvider) ([]repository.NotificationPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].([]repository.NotificationPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheProviderMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacheProvider)(nil).Get), key)
}

// Set mocks base method.
func (m *MockCacheProvider) Set(key repository.NotificationProvider, values []repository.NotificationPreference) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, values)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheProviderMockRecorder) Set(key, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacheProvider)(nil).Set), key, values)
}
