// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/koungkub/fw-challenge-notification-service/internal/repository (interfaces: PersistentProvider)
//
// Generated by this command:
//
//	mockgen -package mockrepository -destination ./mock/mockpersistent.go . PersistentProvider
//

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	reflect "reflect"

	repository "github.com/koungkub/fw-challenge-notification-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockPersistentProvider is a mock of PersistentProvider interface.
type MockPersistentProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPersistentProviderMockRecorder
	isgomock struct{}
}

// MockPersistentProviderMockRecorder is the mock recorder for MockPersistentProvider.
type MockPersistentProviderMockRecorder struct {
	mock *MockPersistentProvider
}

// NewMockPersistentProvider creates a new mock instance.
func NewMockPersistentProvider(ctrl *gomock.Controller) *MockPersistentProvider {
	mock := &MockPersistentProvider{ctrl: ctrl}
	mock.recorder = &MockPersistentProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistentProvider) EXPECT() *MockPersistentProviderMockRecorder {
	return m.recorder
}

// FindByProviderType mocks base method.
func (m *MockPersistentProvider) FindByProviderType(ctx context.Context, provider repository.NotificationProvider) ([]repository.NotificationPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProviderType", ctx, provider)
	ret0, _ := ret[0].([]repository.NotificationPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProviderType indicates an expected call of FindByProviderType.
func (mr *MockPersistentProviderMockRecorder) FindByProviderType(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProviderType", reflect.TypeOf((*MockPersistentProvider)(nil).FindByProviderType), ctx, provider)
}
