// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/koungkub/fw-challenge-notification-service/internal/client (interfaces: HTTPClientProvider)
//
// Generated by this command:
//
//	mockgen -package mockclient -destination ./mock/mockclient.go . HTTPClientProvider
//

// Package mockclient is a generated GoMock package.
package mockclient

import (
	context "context"
	reflect "reflect"

	client "github.com/koungkub/fw-challenge-notification-service/internal/client"
	gomock "go.uber.org/mock/gomock"
)

// MockHTTPClientProvider is a mock of HTTPClientProvider interface.
type MockHTTPClientProvider struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientProviderMockRecorder
	isgomock struct{}
}

// MockHTTPClientProviderMockRecorder is the mock recorder for MockHTTPClientProvider.
type MockHTTPClientProviderMockRecorder struct {
	mock *MockHTTPClientProvider
}

// NewMockHTTPClientProvider creates a new mock instance.
func NewMockHTTPClientProvider(ctrl *gomock.Controller) *MockHTTPClientProvider {
	mock := &MockHTTPClientProvider{ctrl: ctrl}
	mock.recorder = &MockHTTPClientProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClientProvider) EXPECT() *MockHTTPClientProviderMockRecorder {
	return m.recorder
}

// Post mocks base method.
func (m *MockHTTPClientProvider) Post(ctx context.Context, u string, reqBody client.NotificationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", ctx, u, reqBody)
	ret0, _ := ret[0].(error)
	return ret0
}

// Post indicates an expected call of Post.
func (mr *MockHTTPClientProviderMockRecorder) Post(ctx, u, reqBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockHTTPClientProvider)(nil).Post), ctx, u, reqBody)
}
